;
; File generated by cc65 v 2.16 - Git 18b0aaf
;
	.fopt		compiler,"cc65 v 2.16 - Git 18b0aaf"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		__SRAM_SIZE__, __SRAM_RUN__
	.export		_loadsram, _savesram

.include "snes.sinc"

LEN = ptr1
SRC = ptr2
DST = ptr3

.segment	"CODE"

_loadsram:
	phb
	setaxy16

	lda #__SRAM_SIZE__
	sta LEN

	stz SRC

	lda #__SRAM_RUN__
	sta DST

	lda LEN
	dea

	ldx SRC
	ldy DST
; Note the fixed bank! From the save ram to the shadow SRAM section in RAM
	mvn #$70, #$80

	setaxy8
	plb
	rts

_savesram:
	phb
	setaxy16

	lda #__SRAM_SIZE__
	sta LEN

	lda #__SRAM_RUN__
	sta SRC

	stz DST

	lda LEN
	dea

	ldx SRC
	ldy DST
; Note the fixed bank! From the shadow SRAM section in RAM to save ram
	mvn #$80, #$70

	setaxy8
	plb
	rts
