;
; File generated by cc65 v 2.15 - Git 24c2da9
;
	.fopt		compiler,"cc65 v 2.15 - Git 24c2da9"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.exportzp	_curbank
	.importzp	_sneslib_ptr
	.export		_trampoline

; ---------------------------------------------------------------
; void __near__ trampoline (void)
; ---------------------------------------------------------------

.segment	"ZEROPAGE"
_curbank:	.res 1

.segment	"CODE"

.proc	_trampoline: near

	ldy	_curbank
	cpy	tmp4
	bne	jump
	jmp	(ptr4)

; a bankswitch is needed
jump:
	phy
; the current bank is now on stack

	ldy	tmp4
	sty	_sneslib_ptr+2
	sty	_curbank

	ldy	#<here
	sty	_sneslib_ptr
	ldy	#>here
	sty	_sneslib_ptr+1
	jml	[_sneslib_ptr] ; jump to ourself, but in a different bank

here:
	jsr	callptr4

; restore the old bank
	ply

	sty	_sneslib_ptr+2
	sty	_curbank

	ldy	#<done
	sty	_sneslib_ptr
	ldy	#>done
	sty	_sneslib_ptr+1
	jml	[_sneslib_ptr] ; jump to ourself, but in a different bank
done:
	rts

.endproc

